config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server => '/cable'

  resources :rooms do
   resources :messages
  end

  resources :messages
  resources :rooms
  resources :users
  get 'static_pages/index'

  root 'static_pages#index'

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @messages = @room.messages
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:user_id, :room_name)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div> -->

  <div class="field">
    <%= f.label :room_name %>
    <%= f.text_field :room_name, class: 'form-text-field' %>
  </div>

  <div class="actions form-button">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/_messages.html.erb
<div class="message-append">
  <% @messages.each do |message| %>
  <div class="message-wrap"><%= message.user.user_name %>: <%= message.body %>
    <% if signed_in? && current_user.admin? %>
      <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, room_message_path(message.room, message), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
  <div class="message-divider"></div>
  <% end %>
</div>

app/views/rooms/_new_message.html.erb
<% if signed_in? %>
  <%= form_for([@room, @room.messages.build], remote: true) do |f| %>
  <div class="row">
    <div class="message-area col-xs-10 col-sm-10 col-md-11">
      <%= f.text_area :body, class: 'form-control', placeholder:'Type your message..', id:'exampleTextarea', rows:'2' %>
    </div>
    <span>
      <%= button_tag "", type: 'submit', class: "btn btn-default glyphicon glyphicon-send send-message col-xs-2 col-sm-2 col-md-1" %>
      <!-- <%= f.submit "Submit", class:'btn btn-primary send-message col-md-1' %> -->
    </span>
  </div>
  <% end %>
<% end %>

app/views/rooms/_room.html.erb
<div class="col-xs-12 col-sm-6 col-md-3">
  <div class="display-room">
  <% cache room do %>
    <div class="room-description">
      <p class="room-name"><%= room.room_name %></p>
    </div>
    <div class="room-links">
      <span><%= link_to 'Show', room %></span>
      <% if current_user && current_user.admin? %>
        <span><%= link_to 'Edit', edit_room_path(room) %></span>
        <span><%= link_to 'Delete', room, method: :delete, data: { confirm: 'Are you sure?' } %></span>
      <% end %>
    <% end %>
    </div>
  </div>
</div> <!-- /col -->

app/views/rooms/edit.html.erb
<header>
  <h1>Editing room</h1>
</header>
<div class="row">
  <div id="room-form">
    <%= render 'form', room: @room %>
  </div>
</div>
<div class="room-links">
  <%= link_to 'Show', @room %> |
  <%= link_to 'Back', rooms_path %>
</div>

app/views/rooms/index.html.erb
<body class="room-index">
  <header>
    <h1>Chat Rooms</h1>
  </header>
  <div class="row">
    <% @rooms.each do |room| %>
      <%= render partial: "room", locals: {room: room} %>
    <% end %>
  </div>
</body>

app/views/rooms/new.html.erb
<header>
  <h1>New Room</h1>
</header>
<div class="row">
  <div id="room-form">
    <%= render 'form', room: @room %>
  </div>
</div>
<div class="room-links">
  <%= link_to 'Back', rooms_path %>
</div>

app/views/rooms/show.html.erb
<!-- <div class="alert alert-info" style="display:none" role="alert">A new message was posted!</div> -->
<body class="room-show">
  <header>
    <h1><%= @room.room_name %> Chat Room</h1>
  </header>
  <div class="chat-wrapper" data-room-id="<%= @room.id %>">
    <div class="col-xs-12 col-sm-10 col-md-10 chat-position">
      <div class="row">
        <div class="messages room-messages" role="region">
          <%= render partial: "messages", locals: {message: @message} %>
        </div>
      </div>
      <div class="row">
        <% if signed_in? %>
          <div class="messages">
            <%= render partial: "new_message", locals: {message: @message} %>
          </div>
          <% end %>
      </div>
    </div>
  </div>
</body>