config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount ActionCable.server => '/cable'

  resources :rooms do
   resources :messages
  end

  resources :messages
  resources :rooms
  resources :users
  get 'static_pages/index'

  root 'static_pages#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WIM</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-style">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button aria-expanded="false" class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'WIM', root_path, class: 'navbar-brand' %>
        </div><!-- Collect the nav links, forms, and other content for toggling -->

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right link-style">
            <% if user_signed_in? %>
            <div class="btn-group">
              <button type="button" class="btn btn-user dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               <%= link_to(current_user.user_name, users_path) %> <span class="caret"></span>
              </button>
               <ul class="dropdown-menu" role="menu">
                <li><%= link_to('Profile', users_path) %></li>
                <li><%= link_to('Change Passowrd', edit_user_registration_path) %></li>
                <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
                <li class="divider"></li>
                <li><%= link_to 'Create new Room', new_room_path %></li>
               </ul>
             </div>
             <li><%= link_to 'Chat Rooms', rooms_path %></li>
            <% else %>
             <li><%= link_to('Login/Sign up', new_user_session_path) %></li>
             <li><%= link_to 'Chat Rooms', rooms_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

   <div class="page-wrap">
     <div class="container-fluid">
        <% if notice %>
          <div class="alert alert-success" role="alert"><%= notice %></div>
       <% elsif alert %>
         <div class="alert alert-danger" role="alert"><%= alert %></div>
       <% end %>
     </div>

      <%= yield %>

    <div class="push"></div>
    </div>

      <footer id="footer">
        <a class="twitter-follow-button" data-show-count="true" href="https://twitter.com/albertoboz">Follow @albertoboz</a>
          <div class="copyright">
            <p>&copy; WIM 2017</p>
            <p></p>
          </div>
      </footer>
  </body>
</html>